# Generated by Django 5.0.7 on 2024-08-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_app', '0002_game_gamestate_alter_user_visible_username_lobby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='channel_layer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
