# Generated by Django 5.0.7 on 2024-08-23 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_app', '0003_player_channel_layer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='channel_layer',
            new_name='channel_name',
        ),
    ]
