# Generated by Django 5.0.7 on 2024-08-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_app', '0004_rename_channel_layer_player_channel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='state',
        ),
        migrations.AddField(
            model_name='game',
            name='cycle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='view',
            field=models.JSONField(default={}),
        ),
    ]
