# Generated by Django 5.0.7 on 2024-08-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_app', '0005_remove_player_state_game_cycle_player_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='view',
            field=models.JSONField(default=dict),
        ),
    ]
