# Generated by Django 5.0.7 on 2024-08-26 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_app', '0006_alter_player_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleReveal',
            fields=[
                ('gamestate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mafia_app.gamestate')),
                ('current_state', models.IntegerField(choices=[(1, 'Event Info'), (2, 'Moderator Info'), (3, 'Moderator Wait'), (4, 'Event Finished')], default=1)),
                ('order_of_players', models.JSONField()),
                ('current_player', models.IntegerField(default=-1)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('mafia_app.gamestate',),
        ),
    ]
