# Generated by Django 5.0.7 on 2024-08-26 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_app', '0007_rolereveal'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mafia_app.player'),
        ),
    ]
