# Generated by Django 5.0.7 on 2024-09-03 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_app', '0008_game_moderator'),
    ]

    operations = [
        migrations.CreateModel(
            name='MafiaVote',
            fields=[
                ('gamestate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mafia_app.gamestate')),
                ('current_state', models.IntegerField(choices=[(1, 'Moderator Info'), (2, 'Vote'), (3, 'Moderator Result'), (4, 'Event Finished')], default=1)),
                ('votes', models.JSONField()),
                ('mafia_confirm', models.JSONField()),
                ('no_mafiosi', models.IntegerField()),
                ('no_mafiosi_confirmed', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('mafia_app.gamestate',),
        ),
        migrations.CreateModel(
            name='Night',
            fields=[
                ('gamestate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mafia_app.gamestate')),
                ('state_type', models.IntegerField(choices=[(1, 'Event Info'), (2, 'Mafia Vote'), (3, 'Protector Pick'), (4, 'Seer Pick'), (5, 'Event Finished')], default=1)),
                ('current_state', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mafia_app.gamestate')),
                ('mafia_pick', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mafia_app.player')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('mafia_app.gamestate',),
        ),
    ]
