# Generated by Django 5.0.7 on 2024-09-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_app', '0009_mafiavote_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='mafiavote',
            name='mafia_pick',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
