# Generated by Django 5.0.7 on 2024-09-03 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_app', '0011_mafiavote_vote_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='mafiavote',
            name='night_event',
            field=models.ForeignKey(default=48, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mafia_app.night'),
            preserve_default=False,
        ),
    ]
