# Generated by Django 5.0.7 on 2024-09-03 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_app', '0013_remove_mafiavote_vote_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='night',
            name='protector_pick',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mafia_app.player'),
        ),
        migrations.CreateModel(
            name='ProtectorEvent',
            fields=[
                ('gamestate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mafia_app.gamestate')),
                ('current_state', models.IntegerField(choices=[(1, 'Moderator Info'), (2, 'Pick'), (3, 'Moderator Result'), (4, 'Event Finished')], default=1)),
                ('night_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mafia_app.night')),
                ('protector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mafia_app.player')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('mafia_app.gamestate',),
        ),
    ]
