# Generated by Django 5.0.7 on 2024-09-04 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_app', '0015_seerevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='End',
            fields=[
                ('gamestate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mafia_app.gamestate')),
                ('game_result', models.IntegerField(choices=[(1, 'Continue'), (2, 'Mafia Wins'), (3, 'Village Wins')])),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('mafia_app.gamestate',),
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('gamestate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mafia_app.gamestate')),
                ('state_type', models.IntegerField(choices=[(1, 'Event Info'), (2, 'Night Outcome'), (3, 'Discussion'), (4, 'Vote'), (5, 'Event Finished')], default=1)),
                ('current_state', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mafia_app.gamestate')),
                ('previous_night', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_day', to='mafia_app.night')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('mafia_app.gamestate',),
        ),
        migrations.CreateModel(
            name='NightOutcome',
            fields=[
                ('gamestate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mafia_app.gamestate')),
                ('night_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mafia_app.night')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('mafia_app.gamestate',),
        ),
    ]
