# Generated by Django 5.0.7 on 2024-09-04 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_app', '0017_nightoutcome_day_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayVote',
            fields=[
                ('gamestate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mafia_app.gamestate')),
                ('current_state', models.IntegerField(choices=[(1, 'Event Info'), (2, 'Moderator Info'), (3, 'Moderator Wait'), (4, 'Moderator Result'), (5, 'Vote Result'), (6, 'Event Finished')], default=1)),
                ('order_of_players', models.JSONField()),
                ('current_player', models.IntegerField(default=-1)),
                ('votes', models.JSONField()),
                ('day_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mafia_app.day')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('mafia_app.gamestate',),
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('gamestate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mafia_app.gamestate')),
                ('current_state', models.IntegerField(choices=[(1, 'Event Info'), (2, 'Discussion Ongoing'), (3, 'Discussion Finished'), (4, 'Event Finished')], default=1)),
                ('discussion_end_time', models.DateTimeField(blank=True, null=True)),
                ('day_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mafia_app.day')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('mafia_app.gamestate',),
        ),
    ]
