# Generated by Django 5.0.7 on 2024-09-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_app', '0018_dayvote_discussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
