# Generated by Django 5.0.7 on 2024-09-15 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_app', '0020_alter_day_previous_night_alter_dayvote_day_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='states', to='mafia_app.game'),
        ),
    ]
