# Generated by Django 5.0.7 on 2024-09-15 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia_app', '0021_alter_gamestate_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='previous_night',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_day', to='mafia_app.night'),
        ),
        migrations.AlterField(
            model_name='dayvote',
            name='day_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mafia_app.day'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='day_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mafia_app.day'),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='mafia_app.game'),
        ),
        migrations.AlterField(
            model_name='mafiavote',
            name='night_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mafia_app.night'),
        ),
        migrations.AlterField(
            model_name='nightoutcome',
            name='day_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mafia_app.day'),
        ),
        migrations.AlterField(
            model_name='nightoutcome',
            name='night_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mafia_app.night'),
        ),
        migrations.AlterField(
            model_name='protectorevent',
            name='night_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mafia_app.night'),
        ),
        migrations.AlterField(
            model_name='protectorevent',
            name='protector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mafia_app.player'),
        ),
        migrations.AlterField(
            model_name='seerevent',
            name='night_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mafia_app.night'),
        ),
        migrations.AlterField(
            model_name='seerevent',
            name='seer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mafia_app.player'),
        ),
    ]
